feat(#6): Adds configuration parameters to database services
jshiftio/odo-java pull request #15
Opened 2019-04-08 14:02 UTC by lordofthejars

Fixes #6

2019-04-10 06:39 UTC, rohanKanojia approved these changes

2019-04-11 21:07 UTC, devang-gaur requested changes
just a tiny change requested.  everything else looks perfect.

2019-04-11 21:07 UTC, devang-gaur commented on detectors/src/main/java/io/jshift/odo/detectors/DatabaseConfigurationExtractorLoader.java
> +    public List<DatabaseConfigurationExtractor> detectors(Extractor extractor) {
shouldn't this method be called extractors ?

2019-04-11 21:07 UTC, devang-gaur commented on detectors/src/main/java/io/jshift/odo/detectors/DatabaseConfigurationExtractorLoader.java
> +    public List<DatabaseConfigurationExtractor> detectors(Extractor extractor) {
or ConfigExtractor ?

2019-04-12 06:03 UTC, lordofthejars commented on detectors/src/main/java/io/jshift/odo/detectors/DatabaseConfigurationExtractorLoader.java
> +    public List<DatabaseConfigurationExtractor> detectors(Extractor extractor) {
true.

2019-04-12 10:55 UTC, merged